"""Add approval_history table and relationship to tasks

Revision ID: b23d8d850e20
Revises: 8cb21e6d39b2
Create Date: 2025-08-15 08:33:18.771345

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b23d8d850e20'
down_revision: Union[str, None] = '8cb21e6d39b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('approval_history',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('task_id', sa.UUID(), nullable=False),
        sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'FAILED', 'CANCELLED', 'PENDING_APPROVAL', 'APPROVED', 'REJECTED', name='taskstatus'), nullable=False),
        sa.Column('timestamp', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.alter_column('id',
                   existing_type=sa.NUMERIC(),
                   type_=sa.UUID(),
                   existing_nullable=False)
        batch_op.alter_column('status',
                   existing_type=sa.VARCHAR(length=11),
                   type_=sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'FAILED', 'CANCELLED', 'PENDING_APPROVAL', 'APPROVED', 'REJECTED', name='taskstatus'),
                   existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.alter_column('status',
                   existing_type=sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'FAILED', 'CANCELLED', 'PENDING_APPROVAL', 'APPROVED', 'REJECTED', name='taskstatus'),
                   type_=sa.VARCHAR(length=11),
                   existing_nullable=False)
        batch_op.alter_column('id',
                   existing_type=sa.UUID(),
                   type_=sa.NUMERIC(),
                   existing_nullable=False)

    op.drop_table('approval_history')
    # ### end Alembic commands ###
