name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy Frontend to Azure Static Web Apps
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build and Deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "deploy"
          app_location: "frontend"
          output_location: "build"
          app_build_command: |
            npm ci && npm run build
          skip_api_build: true
        env:
          # Optional environment variables can be defined per environment/branch via GitHub Environments
          
          # Example: set custom SWA app name or environment-specific flags here if needed
          # SWA_APP_NAME: my-swa-app
          # NODE_OPTIONS: --max_old_space_size=4096
